#!/bin/bash
onion compile \
    --lib src \
    --lib vendor/pear \
    --classloader \
    --bootstrap scripts/classmap.php \
    --executable \
    --output classmap.phar
chmod +x classmap.phar
mv classmap.phar classmap
