#!/bin/bash
onion compile \
    --lib src \
    --lib vendor/corneltek/universal/src \
    --lib vendor/corneltek/getoptionkit/src \
    --lib vendor/corneltek/cliframework/src \
    --classloader \
    --bootstrap scripts/classmap.php \
    --executable \
    --output classmap.phar
chmod +x classmap.phar
mv classmap.phar classmap
